Strengthen pkg-test
* Define POINTERHOLDER_TRANSITION
* Make sure we are getting the intended version of qpdf

diff --git a/pkg-test/test-cmake b/pkg-test/test-cmake
--- a/pkg-test/test-cmake
+++ b/pkg-test/test-cmake
@@ -11,8 +11,14 @@ if [ ! -d "$TMP" ]; then
     echo 1>&2 "Usage: $0 tmp-dir"
     exit 2
 fi
+
+WANTED_VERSION=$(awk -F'"' '/#define QPDF_VERSION / {print $2}' include/qpdf/DLL.h)
+
 cp pkg-test/qpdf-version.cc pkg-test/CMakeLists.txt $TMP
 cd $TMP
 cmake -S . -B build
 cmake --build build
-./build/qpdf-version
+if [ "$(./build/qpdf-version)" != "$WANTED_VERSION" ]; then
+    echo 1>&2 "Failed to get correct qpdf version from cmake test"
+    exit 2
+fi
diff --git a/pkg-test/test-pkg-config b/pkg-test/test-pkg-config
--- a/pkg-test/test-pkg-config
+++ b/pkg-test/test-pkg-config
@@ -13,11 +13,18 @@ if [ ! -d "$TMP" ]; then
     exit 2
 fi
 
+WANTED_VERSION=$(awk -F'"' '/#define QPDF_VERSION / {print $2}' include/qpdf/DLL.h)
+
 cp pkg-test/qpdf-version.cc $TMP
 cd $TMP
-pkg-config libqpdf --modversion
+if [ "$(pkg-config libqpdf --modversion)" != "$WANTED_VERSION" ]; then
+    echo 1>&2 "Failed to get correct qpdf version from pkg-config --modversion"
+fi
 pkg-config libqpdf --libs --static
 g++ qpdf-version.cc -o qpdf-version \
     $(pkg-config libqpdf --cflags) \
     $(pkg-config libqpdf --libs)
-./qpdf-version
+if [ "$(./qpdf-version)" != "$WANTED_VERSION" ]; then
+    echo 1>&2 "Failed to get correct qpdf version from pkg-config test"
+    exit 2
+fi
